register/urls.py
from django.conf.urls import patterns, url

from register import views
from register.models import Krav, Uppgift

from django.views.generic import TemplateView
urlpatterns = patterns('',
                       url(r'^$', views.IndexView.as_view(), name="index"),
                       url(r'^krav/$', views.KravList.as_view(), name="krav-list"),
                       url(r'^krav/(?P<slug>[A-Z]+\d+)$', views.KravDetail.as_view(), name="krav-detail"),

                       url(r'^kravomrade/$', views.KravomradeList.as_view(), name="kravomrade-list"),
                       url(r'^kravomrade/(?P<pk>\d+)$', views.KravomradeDetail.as_view(), name="kravomrade-detail"),

                       url(r'^uppgift/$', views.UppgiftList.as_view(), name="uppgift-list"),
                       url(r'^uppgift/(?P<slug>[A-Z]+\d+)$', views.UppgiftDetail.as_view(), name="uppgift-detail"),

                       url(r'^form/$', views.ForetagsformList.as_view(), name="form-list"),
                       url(r'^form/(?P<slug>[A-Z]+)$', views.ForetagsformDetail.as_view(), name="form-detail"),

                       url(r'^bransch/$', views.BranschList.as_view(), name="bransch-list"),
                       url(r'^bransch/(?P<slug>[A-Z]+)$', views.BranschDetail.as_view(), name="bransch-detail"),

                       url(r'^myndighet/$', views.MyndighetList.as_view(), name="myndighet-list"),
                       url(r'^myndighet/(?P<pk>\d+)$', views.MyndighetDetail.as_view(), name="myndighet-detail"),

                       url(r'^search/$', views.search, name="search"),


                       url(r'^efter_myndighet.png$', views.img_krav_by_myndighet, name="img_krav_by_myndighet"),
                       url(r'^efter_uppgift.png$', views.img_krav_by_uppgift, name="img_krav_by_uppgift"),
)

uppgiftskrav/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

from django.views.generic import RedirectView

from register.admin import admin_site

urlpatterns = patterns('',
                       # Examples:
                       url(r'^$', RedirectView.as_view(url="/db/")),
                       url(r'^db/', include('register.urls', namespace='register')),
                       url(r'^admin/', include(admin_site.urls)),
                       url(r'^report_builder/', include('report_builder.urls'))
                       # url(r'^admin/', include("massadmin.urls"))
                       )

register/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals, print_function

from django.db import models
from django.db.models.fields import FieldDoesNotExist
from django.contrib.auth import models as authmodels
from django.core.urlresolvers import reverse
from django.core.exceptions import ValidationError

class UppgiftManager(models.Manager):
    def get_by_natural_key(self, uppgiftid):
        return self.get(uppgiftid=uppgiftid)

class Uppgift(models.Model):
    objects = UppgiftManager()
    uppgiftid = models.CharField(max_length=8, unique=True)
    namn = models.CharField(max_length=100)

    def __unicode__(self):
        return "%s: %s" % (self.uppgiftid, self.namn)

    def __iter__(self):
        for i in self._meta.get_all_field_names():
            yield (self._meta.get_field(i), getattr(self, i))

    def natural_key(self):
        return (self.uppgiftid,)

    class Meta():
        verbose_name_plural = "Uppgifter"
        ordering = ["id"]

class VerksamhetsomradeManager(models.Manager):
    def get_by_natural_key(self, omrade):
        return self.get(omrade=omrade)

class Verksamhetsomrade(models.Model):
    objects = VerksamhetsomradeManager()
    omrade = models.CharField("Område", max_length=100, unique=True)
    myndighet = models.ForeignKey(authmodels.Group,
                                  related_name="verksamhetsomrade_for",
                                  help_text="Myndighet som har verksamhetsområdet")

    def __unicode__(self):
        return self.omrade

    def __iter__(self):
        for i in self._meta.get_all_field_names():
            yield (self._meta.get_field(i), getattr(self, i))

    def natural_key(self):
        return (self.omrade,)

    class Meta:
        verbose_name = "Verksamhetsområde"
        verbose_name_plural = "Verksamhetsområden"


class KravomradeManager(models.Manager):
    def get_by_natural_key(self, omrade):
        return self.get(omrade=omrade)

class Kravomrade(models.Model):
    objects = KravomradeManager()
    omrade = models.CharField("Kravområde", max_length=100, unique=True)
    beskrivning = models.TextField("Beskrivning")
    myndighet = models.ForeignKey(authmodels.Group,
                                  related_name="kravomrade_for",
                                  help_text="Myndighet som har definierat kravområdet")

    def __unicode__(self):
        return self.omrade

    def __iter__(self):
        for i in self._meta.get_all_field_names():
            yield (self._meta.get_field(i), getattr(self, i))

    def natural_key(self):
        return (self.omrade,)

    class Meta:
        verbose_name = "Kravområde"
        verbose_name_plural = "Kravområden"

class BranschManager(models.Manager):
    def get_by_natural_key(self, snikod):
        return self.get(snikod=snikod)

class Bransch(models.Model):
    objects = BranschManager()
    snikod = models.CharField("SNI-kod", max_length=1, unique=True)
    beskrivning = models.CharField(max_length=255)

    def __unicode__(self):
        return "%s: %s" % (self.snikod, self.beskrivning)

    def __iter__(self):
        for i in self._meta.get_all_field_names():
            try:
                yield (self._meta.get_field(i),  getattr(self, i))
            except FieldDoesNotExist: # meta.ge_all_field_names returns 'krav' for some reason...
                pass

    def natural_key(self):
        return (self.snikod,)

    class Meta:
        verbose_name_plural = "Branscher"


class ForetagsformManager(models.Manager):
    def get_by_natural_key(self, formkod):
        return self.get(formkod=formkod)

class Foretagsform(models.Model):
    objects = ForetagsformManager()
    formkod = models.CharField("Företagsformskod", max_length=3, unique=True)
    beskrivning = models.CharField(max_length=30)

    def __unicode__(self):
        return "%s: %s" % (self.formkod, self.beskrivning)

    def __iter__(self):
        for i in self._meta.get_all_field_names():
            if hasattr(self, i):
                yield (self._meta.get_field(i), getattr(self, i))

    def natural_key(self):
        return (self.formkod,)

    class Meta:
        verbose_name = "Företagsform"
        verbose_name_plural = "Företagsformer"


class Periodicitet(models.Model):
    beskrivning = models.CharField(max_length=50)

    def __unicode__(self):
        return "%s" % self.beskrivning

    class Meta:
        verbose_name_plural = "Periodiciteter"


class KravManager(models.Manager):
    def get_by_natural_key(self, kravid):
        return self.get(kravid=kravid)
        
# just to save some typing space...    
m2m = models.ManyToManyField
fk = models.ForeignKey
cf = models.CharField
tf = models.TextField
nbf = models.NullBooleanField
bf = models.BooleanField
intf = models.IntegerField
url = models.URLField
datef = models.DateField


def not_empty(value):
    if not value:
        raise ValidationError("Värdet får inte vara tomt")

def not_empty_list(value):
    if not value.all():
        raise ValidationError("Måste ange ett eller flera möjliga val")

def not_null(value):
    if value is None:
        raise ValidationError("Antingen Ja eller Nej måste anges")

def not_null_integer(value):
    if value is None:
        raise ValidationError("Ett tal måste anges")



class Krav(models.Model):
    
    objects = KravManager()
    OKANT = -1
    NEJ = 0
    JA = 1

    verksamhetsomrade = fk(Verksamhetsomrade,
                           blank=True,
                           null=True,
                           verbose_name="Verksamhetsområde",
                           help_text="Indelning som vissa myndigheter själva "
                                     "önskat för att kunna dela upp arbetet.")

    kravomrade = fk(Kravomrade,
                    blank=True,
                    null=True,
                    verbose_name="Kravområde",
                    help_text="Om uppgiftskravet hör till ett redan befintligt och av myndigheten definierat kravområde eller liknande, ange det om det går att återanvända och visa mot kund.")

    ansvarig_myndighet = fk(authmodels.Group,
                            blank=True,
                            null=True,
                            related_name="ansvarig_for",
                            verbose_name="Ansvarig myndighet",
                            help_text="""Myndighet som är ansvarig för ett uppgiftskrav. Samma
                            som kartläggande myndighet utom i de fall
                            insamling sker för annan myndighets  räkning.""")

    kartlaggande_myndighet = fk(authmodels.Group,
                                blank=True,
                                null=True,
                                related_name="kartlaggande_for",
                                verbose_name="Kartläggande myndighet",
                                help_text="""Myndighet som
                                kartlagt uppgiftskravet.""")

    # actual primary key, used in Meta.unique_together    
    kravid = cf("ID",
                unique=True,
                max_length=7,
                help_text="""ID för uppgiftskravet.\nSka inte ändras.""") 

    namn = cf("Uppgiftskrav",
              max_length=255,
              blank=True,
              help_text="""Tydlig och enkel benämning på uppgiftskravet så att företaget förstår vad det innebär.""")

    forfattning = cf("Författning",
                     max_length=50,
                     editable=False,
                     blank=True,
                     help_text="""Beteckning på den lag, förordning eller myndighetsföreskrift som
                     uppgiftskravet finns i.

                     Om författningen är fel ska den inte ändras
                     här. Skriv istället korrekt författning under
                     Författningsstöd.""")

    paragraf = cf(max_length=50,
                  editable=False,
                  blank=True,
                  help_text="""Hänvisning i aktuell författning.

                  Om paragrafen är fel ska den inte ändras här. Skriv istället korrekt
                  författning under Författningsstöd.""")

    lagrum = cf("Författningsstöd",
                max_length=1000,
                blank=True,
                help_text="""Ange primärt författningsstöd där innehållet i
                uppgiftskravet specificeras.

                För EU-lagstiftning: Använd Celexnummer, artikel,
                stycke därefter ev bilaga (t ex 31993R2454 221 2).

                För nationell lagstiftning: Använd
                författningssamlingsförkortning författningsnummer, kapitel,
                paragraf, stycke därefter ev. bilaga (t ex SJFS1995:94 15).

                Om det inte går att avgöra primärt författningsstöd
                åtskilj med semikolon (;).""",
                validators=[not_empty])

    NATIONELLT=1
    EU=2
    URSPRUNG = [(NATIONELLT, "Nationellt"),
                (EU, "EU mm")]
    ursprung = intf(choices=URSPRUNG,
                    blank=True,
                    null=True,
                    help_text='Vilket ursprung författningen har. '
                              'Antingen "EU mm" eller "Nationellt"')

    omfattas_av_tjdir = bf("Omfattas av tjänstedirektivet",
                           default=False,
                           help_text="Detta uppgiftskrav omfattas av EU:s tjänstedirektiv (2006/123/EG)")


    beskrivning = tf(editable=False,
                     blank=True,
                     help_text="""Beskrivning av uppgiftskravet.
    
                     Om beskrivningen är fel ska den inte ändras
                     här. Skriv istället under Kort beskrivning av
                     uppgiftskravet.""")

    anteckning = tf(editable=False,
                    blank=True,
                    help_text="""Anteckning om uppgiftskravet.

                    Ska inte ändras.""")

    kortbeskrivning = tf("Kort beskrivning av uppgiftskravet",
                         blank=True,

register/templates/register/base_generic.html
<!DOCTYPE html>
<html lang="sv">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load bootstrap3 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
  </head>
  <body>
    <div class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span> <!-- ?? -->
          </button>
          <a class="navbar-brand" href="{% url 'register:index' %}">Uppgiftskravsregistret</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
	    <!-- use class="active" for currently active nav -->
            <li><a href="{% url 'register:krav-list' %}">Krav</a></li>
            <li><a href="{% url 'register:kravomrade-list' %}">Kravområden</a></li>
            <li><a href="{% url 'register:uppgift-list' %}">Uppgifter</a></li>
            <li><a href="{% url 'register:myndighet-list' %}">Myndigheter</a></li>
            <li><a href="{% url 'register:bransch-list' %}">Branscher</a></li>
            <li><a href="{% url 'register:form-list' %}">Företagsformer</a></li>
	    {% if not user.is_authenticated %}
            <li><a href="/admin/">Logga in</a></li>
	    {% else %}
	    <li>Inloggad som <b>{{ user }}</b></li>
	    {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
    {% bootstrap_messages %}
    <div class="container">
      <h1>{% block title %}Generic title{% endblock %}</h1>
      {% block content %}
      <p>The amazing content goes here</p>
      {% endblock %}
    </div>
    <div class="container">
      <div class="row">
	<div class="col-md-4">
	  {% block leftgrid %}
	  <h2>leftgrid</h2>
	  <p>Text goes here</p>
	  {% endblock %}
	</div>
	<div class="col-md-4">
	  {% block centergrid %}
	  <h2>centergrid</h2>
	  <p>Text goes here</p>
	  {% endblock %}
	</div>
	<div class="col-md-4">
	  {% block rightgrid %}
	  <h2>rightgrid</h2>
	  <p>Text goes here</p>
	  {% endblock %}
	</div>
      </div>
    </div>
    <div class="container">
      <div class="footer">
        <p>
	  
	</p>
      </div>
    </div>
  </body>
</html>

register/templates/register/bransch_detail.html
{% extends "register/detail_generic.html" %}

register/templates/register/bransch_list.html
{% extends "register/list_generic.html" %}

{% block objecttype %} branscher {% endblock %}
{% block objectitem %} <a href="{% url 'register:bransch-detail' object.snikod %}">{{ object.snikod }}: {{ object.beskrivning }}</a></li> {% endblock %}

register/templates/register/detail_generic.html
{% extends "register/base_generic.html" %}

{% block title %} {{object}} {% endblock %}

{% load register_extras %}
{% block content %}
{% if adminurl %}
<p><a href="{{ adminurl }}" class="btn btn-primary active">Redigera detta krav</a></p>
{% endif %}
{% if validation_errors %}
    <div class="alert alert-danger">
      Det finns problem med informationen om uppgiftskravet -- se de rödmarkerade raderna nedan!
    </div>
{% endif %}
<table class="table table-condensed table-hover">
  <thead>
    <tr>
      <th>Fält</th> <th>Värde</th>
    </tr>
  </thead>
  <tbody>
    {% for field, value in object %}
    <tr>
      <td>
	<strong title="{{field.name}}">{{field.verbose_name}}</strong><br>
	<small>{{field.help_text}}</small>
      </td>
      <td>{{value|swedify:field|linebreaks}}
      {% if validation_errors|getitem:field.name %}
	<p class="alert alert-danger">
	{{validation_errors|getitem:field.name|first}}
	</p>
      {% endif %}
      </td>
    </tr>
{% endfor %}
  </tbody>
</table>
{% endblock %}


{% block leftgrid %} {% endblock %}
{% block centergrid %} {% endblock %}
{% block rightgrid %} {% endblock %}

register/templates/register/foretagsform_list.html
{% extends "register/list_generic.html" %}

{% block objecttype %} företagsformer {% endblock %}
{% block objectitem %} <a href="{% url 'register:form-detail' object.formkod %}">{{ object.formkod }}: {{ object.beskrivning }}</a></li> {% endblock %}

register/templates/register/krav_detail.html
{% extends "register/base_generic.html" %}

{% block title %} {{object}}
{% if adminurl %}
<a href="{{ adminurl }}" class="btn btn-primary active">Redigera detta</a>
{% endif %}
{% endblock %}

{% load register_extras %}
{% block content %}
{% if validation_errors %}
    <div class="alert alert-danger">
      Det finns problem med informationen om uppgiftskravet -- se de rödmarkerade raderna nedan!
    </div>
{% endif %}


<table class="table table-condensed table-hover">
  <thead>
    <tr>
      <th>Fält</th> <th>Värde</th>
    </tr>
  </thead>
  <tbody>
    {% for fieldset in fieldsets %}
    <tr><td colspan="2"><h2>{{fieldset.0}}</h2></td></tr>
    {% for fieldname in fieldset.1.fields %}
    <tr>
      <td>
	<strong title="{{field.name}}">{{ object|verbose_name:fieldname }}</strong><br>
	<small>{{ object|help_text:fieldname }}</small>
      </td>
      <td>{{ object|get_value:fieldname|safe }}</td>
      <td>
      {% if validation_errors|getitem:fieldname %}
	<p class="alert alert-danger">
	{{validation_errors|getitem:fieldname|first}}
	</p>
      {% endif %}
      </td>
    </tr>
    {% endfor %}
    {% endfor %}
  </tbody>
</table>
{% endblock %}

{% block leftgrid %}
<h2>Uppgifter</h2>
<ul>
  {% for uppgift in krav.uppgifter.all %}
  <li><a href="{% url 'register:uppgift-detail' uppgift.uppgiftid %}">{{ uppgift }}</a></li>
  {% endfor %}
</ul>
{% endblock %}

{% block centergrid %}
<h2>Branscher</h2>
<ul>
  {% for bransch in krav.bransch.all %}
  <li><a href="{% url 'register:bransch-detail' bransch.snikod %}">{{ bransch }}</a></li>
  {% endfor %}
</ul>
{% endblock %}

{% block rightgrid %}
<h2>Företagsformer</h2>
<ul>
  {% for form in krav.foretagsform.all %}
  <li><a href="{% url 'register:form-detail' form.formkod %}">{{ form }}</a></li>
  {% endfor %}
</ul>
{% endblock %}

register/templates/register/krav_list.html
{% extends "register/list_generic.html" %}

{% block objecttype %} uppgiftskrav {% endblock %}
{% block objectitem %}
  {% if not object.valid %}
     <span style="color: red" class="glyphicon glyphicon-remove"></span>
  {% endif %}
  <a href="{% url 'register:krav-detail' object.kravid %}">{{ object.kravid }}: {{ object.namn }}</a>

{% endblock %}

register/templates/register/kravomrade_detail.html
{% extends "register/detail_generic.html" %}

{% block content %}

<h3>Används i {{ object.krav_set.count }} krav</h3>
<p><b>{{ object.myndighet }}</b></p>
<blockquote>{{ object.beskrivning }}</blockquote>
<ul>
{% for krav in object.krav_set.all %}
<li>
  {% if not krav.valid %}
     <span style="color: red" class="glyphicon glyphicon-remove"></span>
  {% endif %}

  <a href="{{krav.get_absolute_url}}">{{krav}}</a></li>
{% endfor %}
</ul>

{% endblock %}

register/templates/register/kravomrade_list.html
{% extends "register/list_generic.html" %}

{% block objecttype %} kravområden {% endblock %}
{% block objectitem %} <a href="{% url 'register:kravomrade-detail' object.id %}">{{ object.omrade }}</a> <i>"{{object.beskrivning|truncatewords:10}}"</i>, {{ object.myndighet }}</li> {% endblock %}

register/templates/register/list_generic.html
{% extends "register/base_generic.html" %}

{% block title %} Alla {{ paginator.count }} {% block objecttype %} objekt {% endblock %} {% endblock %}

{% block content %}
<ul>
  {% for object in object_list %}
  <li>{% block objectitem %}{{object}}{% endblock %}</li>
  {% endfor %}
</ul>
  {% if paginator.num_pages > 1 %}
  <ul class="pager">
    {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}">Föregående</a>
    {% endif %}
    <span class="current">
      Sida {{ page_obj.number }} av {{ paginator.num_pages }}.
    </span>
    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">Nästa</a>
    {% endif %}
  </ul>
  {% endif %}
{% endblock %}

{% block leftgrid %} {% endblock %}
{% block centergrid %} {% endblock %}
{% block rightgrid %} {% endblock %}

register/templates/register/myndighet_detail.html
{% extends "register/detail_generic.html" %}

{% block title %} {{object}} <small> {{ object.ansvarig_for.count }} uppgiftskrav</small> {% endblock %}

{% block content %}
<ul>
{% for krav in object.ansvarig_for.all %}
<li>
  {% if not krav.valid %}
     <span style="color: red" class="glyphicon glyphicon-remove"></span>
  {% endif %}
  <a href="{{krav.get_absolute_url }}">{{krav}}</a></li>
{% endfor %}
</ul>
{% endblock %}

register/templates/register/myndighet_list.html
{% extends "register/list_generic.html" %}

{% block objecttype %} myndigheter {% endblock %}
{% block objectitem %} <a href="{% url 'register:myndighet-detail' object.id %}">{{ object }}</a></li> {% endblock %}

register/templates/register/search.html
{% extends "register/list_generic.html" %}
{% block title %} Sök uppgiftskrav {% endblock %}
{% block content %}
<form action="{% url 'register:search' %}" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
   <tr>
     <td><input type="reset" value="Nollställ" /></td>
     <td><input type="submit" value="Sök" /></td>
  </table>
</form>
{% if resultset %}
<h2>Resultat: {{resultcount}} krav <small>Varav {{incompletecount}} st
({{incompletepercentage}}%) ickefullständiga</small></h2>

<ul>
{% for object in resultset %}
<li>
  {% if not object.valid %}
     <span style="color: red" class="glyphicon glyphicon-remove"></span>
  {% endif %}
  <a href="{% url 'register:krav-detail' object.kravid %}">{{ object.kravid }}: {{ object.namn }}</a>

</li>
{% endfor %}
</ul>

{% endif %}
{% endblock  %}

{% block leftgrid %} {% endblock %}
{% block centergrid %} {% endblock %}
{% block rightgrid %} {% endblock %}

register/templates/register/uppgift_detail.html
{% extends "register/detail_generic.html" %}

{% block content %}
<h3>Används i {{ object.krav_set.count }} krav</h3>

<ul>
{% for krav in object.krav_set.all %}
<li>
  {% if not krav.valid %}
     <span style="color: red" class="glyphicon glyphicon-remove"></span>
  {% endif %}

  <a href="{{krav.get_absolute_url}}">{{krav}}</a></li>
{% endfor %}
</ul>

{% endblock %}